---
- name: Configure jumphost for User
  hosts: jumphost
  become: True
  tags:
    - jumphost
  vars:
    demo_user: demouser

  roles:

  - name: configure jumphost for user
    role: jumphost_user
    jumphost_user: "{{ demo_user }}"
    tags:
      - jumphost

- name: Configure GitLab for User
  hosts: localhost
  tags:
    - gitlab
  vars:
    demo_user: demouser

  pre_tasks:

  - name: install pyapi-gitlab
    pip:
      name: pyapi-gitlab
    become: yes

  roles:

  - name: configure gitlab for user
    role: gitlab_user
    gitlab_user: "{{ demo_user }}"
    tags:
      - gitlab

